### ISSUE TITLE
Store memeadviser.log in the repo's wiki

### ISSUE THREAD

**Issue by paramt** [paramt/MemeAdviser#13]
### Advantages
The log can be viewed online in real-time

### Implementation
One way to do this is to save the log file in `MemeAdviser.wiki` and run a shell script each time the program runs that looks like this:
```sh
#!/bin/bash
cd MemeAdviser.wiki/
git add .
git commit -m "Update log"
git push
```

**Comment by RDIL** [comment]
I added a copyright footer to the wiki FYI :)

**Comment by paramt** [comment]
Great, thanks 👍

**Comment by paramt** [comment]
[`memeadviser.log`](https://raw.githubusercontent.com/wiki/paramt/MemeAdviser/memeadviser.log) added in #14
