### ISSUE TITLE
Script takes more than 1 minute to run

### ISSUE THREAD

**Issue by paramt** [paramt/MemeAdviser#17]
**Description**
The cronjob is scheduled to run every minute, but this is a problem when the bot has to send 100+ PMs because it takes more than 1 minute to execute and is interrupted by the next scheduled job before it gets a chance to finish
https://github.com/paramt/MemeAdviser/blob/aab7e5a9f2d173d5af8596c8962fd7a8468316ae/src/app.py#L121-L122

**Possible Solutions**
- [run-one](http://manpages.ubuntu.com/manpages/trusty/man1/run-one.1.html)

**Comment by RDIL** [comment]
Delay the cron job?

**Comment by paramt** [comment]
I'm currently trying out `run-one`, and if it doesn't work then we can schedule the job to run every 2 or 3 minutes...

**Comment by paramt** [comment]
[This seems to be fixed](https://www.param.me/MemeAdviser/log/) by `one-run`

![image](https://user-images.githubusercontent.com/23563074/58288474-adb3b680-7d81-11e9-84e3-c234afc575a0.png)
